In [4]:
import numpy as np
A = np.array([1,2,3])
B = np.array([4,3,0])
print('A+B = ',np.add(A,B))
print('A-B = ',np.subtract(A,B))

A+B =  [5 5 3]
A-B =  [-3 -1  3]


In [5]:
C = np.array([[1,2,3],
             [1,1,1]])
D = np.array([[4,3,9,9],
              [1,1,2,2],
              [4,2,1,1]])
#矩阵乘法，C的每行*D的每列
print('np.dot(C,D)) = ',np.dot(C,D))
print('np.matmul(C,D)) = ',np.matmul(C,D))
print('       C@D      =',np.matmul(C,D))
#元素乘法
print('np.multiply(D,D)) = ',np.multiply(D,D))
print('       D@D      =',D*D)

np.dot(C,D)) =  [[18 11 16 16]
 [ 9  6 12 12]]
np.matmul(C,D)) =  [[18 11 16 16]
 [ 9  6 12 12]]
       C@D      = [[18 11 16 16]
 [ 9  6 12 12]]
np.multiply(D,D)) =  [[16  9 81 81]
 [ 1  1  4  4]
 [16  4  1  1]]
       D@D      = [[16  9 81 81]
 [ 1  1  4  4]
 [16  4  1  1]]


np.dot&np.matmul
-都是矩阵乘法
-np.matmul中，禁止矩阵与标量的乘法
-np.matmul中，在矢量乘矢量的内积运算中，matmul与dot无差别
-np.matmul中，多为的矩阵，将前n-2维视为后2维的元素后，进行乘法操作

In [7]:
t1 = np.array([1,2,3])
t2 = np.array([1,2,3])
print(np.dot(t1,t2))
print(np.matmul(t1,t2))
print(t1*t2)

14
14
[1 4 9]


In [8]:
a = np.array([1,2,3])
b = np.array([[1,1,1],
            [2,2,2],
            [3,3,3]])

In [9]:
np.dot(a,b)

array([14, 14, 14])

In [10]:
np.matmul(a,b)

array([14, 14, 14])

In [11]:
a*b

array([[1, 2, 3],
       [2, 4, 6],
       [3, 6, 9]])

In [12]:
m_4_4 = np.array([[1,2,3,4],
                  [3,2,1,4],
                  [5,4,6,7],
                  [11,12,13,14]
                 ])
m_3_4_2 = np.array([[[2,3],
                    [11,9],
                    [32,21],
                     [28,17]],
                    
                    [[2,3],
                    [1,9],
                    [3,21],
                    [28,7]],
                    
                    [[2,3],
                    [1,9],
                    [3,21],
                    [28,7]]
                   ])

In [13]:
print(m_4_4.shape)
print(m_3_4_2.shape)

(4, 4)
(3, 4, 2)


In [14]:
print('4x4*3x4x2 dot:\n {}\n'.format(np.dot(m_4_4,m_3_4_2)))
print('4x4*3x4x2 matmul:\n {}\n'.format(np.matmul(m_4_4,m_3_4_2)))

4x4*3x4x2 dot:
 [[[232 152]
  [125 112]
  [125 112]]

 [[172 116]
  [123  76]
  [123  76]]

 [[442 296]
  [228 226]
  [228 226]]

 [[962 652]
  [465 512]
  [465 512]]]

4x4*3x4x2 matmul:
 [[[232 152]
  [172 116]
  [442 296]
  [962 652]]

 [[125 112]
  [123  76]
  [228 226]
  [465 512]]

 [[125 112]
  [123  76]
  [228 226]
  [465 512]]]



In [15]:
print('4 4 矩阵 与')
print('3 4 2 矩阵的乘积结果')
print('dot 结果的维度 =',np.dot(m_4_4,m_3_4_2).shape)
print('matmul结果的维度 =',np.matmul(m_4_4,m_3_4_2).shape)

4 4 矩阵 与
3 4 2 矩阵的乘积结果
dot 结果的维度 = (4, 3, 2)
matmul结果的维度 = (3, 4, 2)


In [16]:
np.dot(m_4_4,m_3_4_2[0,:,:])

array([[232, 152],
       [172, 116],
       [442, 296],
       [962, 652]])

In [17]:
np.matmul(m_4_4,m_3_4_2[:,:,0].T)

array([[232, 125, 125],
       [172, 123, 123],
       [442, 228, 228],
       [962, 465, 465]])

np.dot定义：
dot(a,b)[i,j,k,m] = sum(a[i,j,:]*b[k,:,m])

In [19]:
import sklearn

In [20]:
from sklearn import datasets
from sklearn.metrics import auc
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso

In [1]:
import tensorflow as tf

ModuleNotFoundError: No module named 'tensorflow'

**黑体**

*斜体*

>引用

* 列出几个观点
* 不带序号
    * 子观点

1. 列出我的观点
2. 带序号
3. 序号后需有空格
4. 生成的序号与你输入的数字无关
    * 子观点

$\pi$

插入数学符号
$e^{i\pi}+1 = 0$

$\sum_{\forall i}{x_i^{2}}$

\begin{align}
\dot{x} & = \sigma(y-x) \\
\dot{y} & = \rho x - y - xz \\
\dot{z} & = -\beta z+xy
\end{align}


插入图片方法

![随意]（图片地址）

<img src='.\psb.jpg',width=200>

In [1]:
from Ipython.display import Image

ModuleNotFoundError: No module named 'Ipython'

In [ ]:
Image(filename='地址',width=200)

插入表格

| 第一栏        | 第二栏           | 第三栏  |
| ------------- |:---------------:| -----:|
| col 3 is       | right-aligned |1600 |
| col 2 is       |centered      |   12 |
| zebra stripes | are neat      |    1  |